name: Update Activity

on:
  schedule:
    - cron: "0 */6 * * *"   # Runs every 6 hours (highly reliable on GitHub's servers)
  workflow_dispatch:        # Allows manual triggering
  push:
    branches:
      - main                # Automatically runs if you manually push a change to the repo

permissions:
  contents: write

jobs:
  update-readme:
    name: Update README with latest GitHub activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update GitHub Activity in README
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          COMMIT_MSG: "chore: update activity feed"
          MAX_LINES: 5
